// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: Ambiente
			/// 2D
			/// </summary>
			public const string Ambiente = "Ambiente";

			/// <summary>
			/// Tag: Antorcha
			/// 2D
			/// </summary>
			public const string Antorcha = "Antorcha";

			/// <summary>
			/// Tag: Arrastrar
			/// 2D
			/// </summary>
			public const string Arrastrar = "Arrastrar";

			/// <summary>
			/// Tag: Cerdo
			/// 2D
			/// </summary>
			public const string Cerdo = "Cerdo";

			/// <summary>
			/// Tag: Golpe
			/// 2D
			/// </summary>
			public const string Golpe = "Golpe";

			/// <summary>
			/// Tag: Interruptor
			/// 2D
			/// </summary>
			public const string Interruptor = "Interruptor";

			/// <summary>
			/// Tag: Madera
			/// 2D
			/// </summary>
			public const string Madera = "Madera";

			/// <summary>
			/// Tag: Musica
			/// 2D
			/// </summary>
			public const string Musica = "Musica";

			/// <summary>
			/// Tag: Pasos
			/// 2D
			/// </summary>
			public const string Pasos = "Pasos";

			/// <summary>
			/// Tag: Planta
			/// 2D
			/// </summary>
			public const string Planta = "Planta";

			/// <summary>
			/// Tag: Pocion
			/// 2D
			/// </summary>
			public const string Pocion = "Pocion";

			/// <summary>
			/// Tag: Puerta
			/// 2D
			/// </summary>
			public const string Puerta = "Puerta";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: Cerdo_Tipo
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string Cerdo_Tipo = "Cerdo_Tipo";

			/// <summary>
			/// Variable: Musica_Tipo
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string Musica_Tipo = "Musica_Tipo";

		}

		public class Channels
		{
			public const string Master = "Master";

		}
	}
}
